### ISSUE TITLE
Auslanderbehorde service seems to get auto-logged out

### ISSUE THREAD

**Issue by PejmanPoh** [gabrielgiordan/berlin-service-portal-bots#3]
Hey @gabrielgiordan,

I'm so happy someone else has had to go through the pain of trying to automate this page. I have been struggling myself and decided to search to see if anyone else has tried. Nice to see yours!
 
I'm trying to use the auslanderbehorde service but it never gets past the "Loading appointment page". It seems like before it can accept the terms and conditions, the page gets logged out. I suppose it has something to do with the chrome client being used? The URL is correct. I'm not python pro so I can't really tell what's going wrong. Any chance you could take a look? Would really help me out :)

**Comment by PejmanPoh** [comment]
I managed to write my own JS bot using Tampermonkey to get an appointment so I don't need this solution anymore. Thanks!

**Comment by blessonabraham** [comment]
@PejmanPoh It would be great if you could share or point to somewhere to get a solution for Tampermonkey because I'm too struggling to get an appointment.

**Comment by markus-azer** [comment]
Hi @PejmanPoh did you find way to solve it?

**Comment by PejmanPoh** [comment]
@markus-azer, I did not.
